-- https://school.programmers.co.kr/learn/courses/30/lessons/157339

WITH CANDIDATES AS(
    SELECT  
        CAR_ID, 
        CAR_TYPE, 
        DAILY_FEE
    FROM 
        CAR_RENTAL_COMPANY_CAR
    WHERE 
        CAR_TYPE IN ('세단','SUV')
), RENTED AS (
    SELECT 
        DISTINCT CAR_ID
    FROM 
        CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE 
        (TO_DATE('2022-11-01','YYYY-MM-DD') BETWEEN START_DATE AND END_DATE
        OR TO_DATE('2022-11-30','YYYY-MM-DD') BETWEEN START_DATE AND END_DATE)
), DISCOUNT_INFO AS (
    SELECT 
        CAR_TYPE, 
        1-(DISCOUNT_RATE/100) AS RATE
    FROM 
        CAR_RENTAL_COMPANY_DISCOUNT_PLAN
    WHERE 
        CAR_TYPE IN ('세단','SUV')
    AND DURATION_TYPE = '30일 이상'
)

SELECT A.CAR_ID
      ,A.CAR_TYPE
      ,TO_NUMBER(A.DAILY_FEE*30*RATE) AS FEE
FROM 
    CANDIDATES A
LEFT OUTER JOIN 
    RENTED B
ON  A.CAR_ID = B.CAR_ID
LEFT OUTER JOIN 
    DISCOUNT_INFO C
ON A.CAR_TYPE = C.CAR_TYPE
WHERE 
    B.CAR_ID IS NULL
AND TO_NUMBER(A.DAILY_FEE*30*RATE) BETWEEN 500000 AND 2000000
ORDER BY 
    TO_NUMBER(A.DAILY_FEE*30*RATE) DESC, 
    A.CAR_TYPE, 
    A.CAR_ID DESC
;